#!/bin/zsh

if [[ $(curl https://raw.githubusercontent.com/Ferbez/virtual-succubus-macos/main/version) -gt 1.5 ]]; then
	osascript -e 'display alert "New version of Virtual Succubus wrapper is available!" message "Please, download and use an updated version."'
	exit
fi

if [ ! -f "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus/Virtual Succubus.exe" ]; then
	WINEDLLOVERRIDES="winedevice.exe=d" DYLD_FALLBACK_LIBRARY_PATH="$(dirname "$0")/../Frameworks" WINEMSYNC=1 WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDEBUG="-all" "$(dirname "$0")/../Resources/wine/bin/wine64" regedit "$(dirname "$0")/../Resources/windowed.reg"
	mkdir "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus"
	if [ ! -d "$HOME/Library/Application Support/SuccuDev" ]; then
		mkdir "$HOME/Library/Application Support/SuccuDev"
	fi
	ln -s "$HOME/Library/Application Support/SuccuDev" "$(dirname "$0")/../Resources/prefix/drive_c/users/$(id -un)/AppData/LocalLow/SuccuDev"
	cd "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus"
	while [ ! -f "$ARCHIVEPATH" ]; do
		ARCHIVEPATH=$(osascript -e 'set archivePath to POSIX path of (choose file with prompt "Please select Virtual Succubus installation archive:" of type {"zip"})')
		if [ ! $ARCHIVEPATH ]; then
			exit 0
		fi
	done
	bsdtar --strip-components=1 -xvf "$ARCHIVEPATH"
	osascript -e 'display alert "Virtual Succubus is successfully installed!" message "Restart an application in order to run it."'
else
	if [ ! -d "$HOME/Library/Application Support/SuccuDev" ]; then
		mkdir "$HOME/Library/Application Support/SuccuDev"
	fi
	cd "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus"
	exec env WINEDLLOVERRIDES="winedevice.exe=d" DYLD_FALLBACK_LIBRARY_PATH="$(dirname "$0")/../Frameworks" WINEMSYNC=1 WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDEBUG="-all" "$(dirname "$0")/../Resources/wine/bin/wine64" "C:/Program Files/Virtual Succubus/Virtual Succubus.exe"
fi
