#!/bin/zsh

if [[ $(curl https://raw.githubusercontent.com/Ferbez/virtual-succubus-macos/main/version) -gt 1.4 ]]; then
	osascript -e 'display alert "New version of Virtual Succubus wrapper is available!" message "Please, download and use an updated version."'
	exit
fi

if [ ! -f "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus/Virtual Succubus.exe" ]; then
	if [[ ( $(uname -m) = "arm64" ) && ( $(sw_vers -productVersion) -ge 14.0 ) ]]; then
		DYLD_FALLBACK_LIBRARY_PATH="$(dirname "$0")/../Frameworks" WINEESYNC=1 WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDEBUG="-all" "$(dirname "$0")/../Resources/wine/bin/wine64" regedit "$(dirname "$0")/../Resources/windowed.reg"
	else
		WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDEBUG="-all" "$(dirname "$0")/../Resources/wine_intel/bin/wine64" regedit "$(dirname "$0")/../Resources/windowed.reg"
		cp "$(dirname "$0")/../Resources/dxvk/x32/dxgi.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/system32/dxgi.dll"
		cp "$(dirname "$0")/../Resources/dxvk/x32/d3d11.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/system32/d3d11.dll"
		cp "$(dirname "$0")/../Resources/dxvk/x32/d3d10core.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/system32/d3d10core.dll"
		cp "$(dirname "$0")/../Resources/dxvk/x64/dxgi.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/syswow64/dxgi.dll"
		cp "$(dirname "$0")/../Resources/dxvk/x64/d3d11.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/syswow64/d3d11.dll"
		cp "$(dirname "$0")/../Resources/dxvk/x64/d3d10core.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/syswow64/d3d10core.dll"
	fi
	mkdir "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus"
	if [ ! -d "$HOME/Library/Application Support/SuccuDev" ]; then
		mkdir "$HOME/Library/Application Support/SuccuDev"
	fi
	ln -s "$HOME/Library/Application Support/SuccuDev" "$(dirname "$0")/../Resources/prefix/drive_c/users/crossover/AppData/LocalLow/SuccuDev"
	cd "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus"
	while [ ! -f "$ARCHIVEPATH" ]; do
		ARCHIVEPATH=$(osascript -e 'set archivePath to POSIX path of (choose file with prompt "Please select Virtual Succubus installation archive:" of type {"zip"})')
		if [ ! $ARCHIVEPATH ]; then
			exit 0
		fi
	done
	bsdtar --strip-components=1 -xvf "$ARCHIVEPATH"
	osascript -e 'display alert "Virtual Succubus is successfully installed!" message "Restart an application in order to run it."'
else
	cd "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus/"
	if [[ ( $(uname -m) = "arm64" ) && ( $(sw_vers -productVersion) -ge 14.0 ) ]]; then
		DYLD_FALLBACK_LIBRARY_PATH="$(dirname "$0")/../Frameworks" WINEESYNC=1 WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDEBUG="-all" "$(dirname "$0")/../Resources/wine/bin/wine64" "C:/Program Files/Virtual Succubus/Virtual Succubus.exe"
	else
		WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDLLOVERRIDES="dxgi,d3d11,d3d10core=n,b" WINEDEBUG="-all" "$(dirname "$0")/../Resources/wine_intel/bin/wine64" "C:/Program Files/Virtual Succubus/Virtual Succubus.exe" "-force-feature-level-10-1"
	fi
fi
