#!/usr/bin/env arch -x86_64 bash

if [ ! -f "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus/Virtual Succubus.exe" ]; then
	WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDEBUG="-all" "$(dirname "$0")/wine64" regedit "$(dirname "$0")/../Resources/windowed.reg"
	rm "$(dirname "$0")/../Resources/windowed.reg"
	cp "$(dirname "$0")/../Resources/dxvk/x32/dxgi.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/system32/dxgi.dll"
	cp "$(dirname "$0")/../Resources/dxvk/x32/d3d11.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/system32/d3d11.dll"
	cp "$(dirname "$0")/../Resources/dxvk/x32/d3d10core.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/system32/d3d10core.dll"
	cp "$(dirname "$0")/../Resources/dxvk/x64/dxgi.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/syswow64/dxgi.dll"
	cp "$(dirname "$0")/../Resources/dxvk/x64/d3d11.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/syswow64/d3d11.dll"
	cp "$(dirname "$0")/../Resources/dxvk/x64/d3d10core.dll" "$(dirname "$0")/../Resources/prefix/drive_c/windows/syswow64/d3d10core.dll"
	rm -rf "$(dirname "$0")/../Resources/dxvk/"
	mkdir "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus"
	if [ ! -d "$HOME/Library/Application Support/SuccuDev" ]; then
		mkdir "$HOME/Library/Application Support/SuccuDev"
	fi
	ln -s "$HOME/Library/Application Support/SuccuDev" "$(dirname "$0")/../Resources/prefix/drive_c/users/crossover/AppData/LocalLow/SuccuDev"
	cd "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus"
	while [ ! -f "$ARCHIVEPATH" ]; do
		ARCHIVEPATH=$(osascript -e 'set archivePath to POSIX path of (choose file with prompt "Please select Virtual Succubus installation archive:" of type {"zip"})')
		if [ ! $ARCHIVEPATH ]; then
			exit 0
		fi
	done
	bsdtar --strip-components=1 -xvf "$ARCHIVEPATH"
	osascript -e 'display alert "Virtual Succubus is successfully installed!" message "Restart an application in order to run it."'
else
	cd "$(dirname "$0")/../Resources/prefix/drive_c/Program Files/Virtual Succubus/"
	WINEPREFIX="$(dirname "$0")/../Resources/prefix" WINEDLLOVERRIDES="dxgi,d3d11,d3d10core=n,b" WINEDEBUG="-all" "$(dirname "$0")/wine64" "C:/Program Files/Virtual Succubus/Virtual Succubus.exe" "-force-feature-level-10-1"
fi
