#!/bin/sh

if [ ! -f "$(dirname "$0")/../Resources/prefix/drive_c/Program Files (x86)/Virtual Succubus/Virtual Succubus.exe" ]; then
	cd "$(dirname "$0")/../../.."
	while [ ! -f "$ARCHIVEPATH" ]; do
		ARCHIVEPATH=$(osascript -e 'set archivePath to POSIX path of (choose file with prompt "Please select VS installation archive:" of type {"zip"})')
		if [ ! $ARCHIVEPATH ]; then
			exit 0
		fi
	done
	FOLDERNAME=$(basename "$ARCHIVEPATH" .zip)
	unzip "$ARCHIVEPATH" -d "Virtual Succubus.app/Contents/Resources/prefix/drive_c/Program Files (x86)"
	mv "Virtual Succubus.app/Contents/Resources/prefix/drive_c/Program Files (x86)/$FOLDERNAME" "Virtual Succubus.app/Contents/Resources/prefix/drive_c/Program Files (x86)/Virtual Succubus"
	osascript -e 'display alert "Virtual Succubus is successfully installed!" message "Restart an application in order to run it."'
else
	if [ ! -d "$HOME/Library/Application Support/SuccuDev/" ]; then
		echo "wrapper: SuccuDev directory not present, creating one"
		mkdir "$HOME/Library/Application Support/SuccuDev/"
	else
		echo "wrapper: SuccuDev directory is present, starting wrapper"
	fi

	cd "$(dirname "$0")/../Resources/prefix/drive_c/"

	export WINEPREFIX="$(dirname "$0")/../Resources/prefix/"
	export WINEARCH="win64"
	export WINEDEBUG=""

	../../../MacOS/wine64 "C:/Program Files (x86)/Virtual Succubus/Virtual Succubus.exe" "-force-feature-level-10-1"
fi
